### ISSUE TITLE
A staticAToken user can be owed a large amount of a reward by the staticAToken if it's not yet registered

### ISSUE THREAD

**Issue by MichaelMorami** [bgd-labs/static-a-token-v3#30]
## Summary:
The bug occurs when a reward token (say bad_reward`) is distributed through the `INCENTIVES_CONTROLLER to a reward-bearing token that the StaticAToken holds, but it is not registered in the StaticATokenLM reward list. In such a state, a user can invoke any claim method with an array that contains this bad_reward. Since the reward is not registered in the system, the user’s rewardsIndexOnLastInteraction will be 0 by default. When, down the stream, getClaimableRewards will be called, the following lines will determine the rewardsIndexOnLastInteraction that is sent to determine the pending rewards:

```
currentUserRewardsData.rewardsIndexOnLastInteraction == 0
          ? _startIndex[reward]
          : currentUserRewardsData.rewardsIndexOnLastInteraction,
```

Since the reward isn’t registered, the user’s index has never been updated. In addition, since the reward isn’t registered the startIndex is 0. that means that the pending rewards will be calculated as:

```
balance * (currentRewardsIndex - rewardsIndexOnLastInteraction)) /
      assetUnit;
```

That means the current reward index of the reward in the incentive controller times the user’s balance. This will make the staticAToken owe a large amount of rewards to any user that will claim before the registration of the asset.
In fact, the staticAToken may owe one or more of its users a larger amount than the incentive owes to the static Token.
Other variation of this bug can also be found of the reward gets registered after some time of being distributed to the static token via the incentive controller

*Concrete Example:*
- Take an initialised staticAToken that just started to work with a list of 3 reward tokens that deserved to be collected thanks to the distribution of the incentive controller.

- On initialisation of the contract will make sure to register those 3 tokens in the staticToken internal list.

- User1 is depositing for the first time at time t which updates his user state, i.e. unclaimed and snapshot of the index at time of operation.

- At time t' > t a new token, `bad_reward` , is being added to the list of rewards that the staticAToken is eligible to claim.

- Nobody refreshes the reward list in the StaticAToken.

- User1 make any action he desires, including depositing a lot of money

- At time t'' > t', after some bad_reward`s are starting to accumulate in the incentive controller to the staticToken right, user1 (maliciously or by mistake) realizes that he’s eligible for his share of `bad_reward and tries to claim it.

- Since the rewards aren’t registered, the user’s rewardsIndexOnLastInteraction is never being updated and is staying at the default value of 0.

- The pending rewards that staticToken is now owed to the user is user_balance * (currentIndex - 0).

- It’s easy to see that this value can be greater than the value actually owed by the incentive controller to the staticAToken - if user1 is the only user in the system staticAToken.balanceOf(user) = incentiveController.balanceOf(asset, reward, staticAToken) , however the current index of the staticAToken on the incentive controller must be greater than 0 because the reward-bearing token (AToken in this case) makes sure to update the code upon transfer (in handleAction ).

See a concrete example that drew our attention to this:
Report - (https://vaas-stg.certora.com/output/99352/e66fdf58d5cc40a98b221cde41ea9fbe/?anonymousKey=bed6acb640c0497a98bef52a5f6edbee94fc5bbc)

In this example, we call getClaimableRewards and get a certain value. The reward isn’t registered in the reward list of the static token, so the if-else in getClaimableRewards will compute the pending rewards as currentIndex - 0. next, we call refresh which registers the reward and takes a snapshot of the index at that time into startIndex. The if-else in getClaimableRewards will now use the startIndex and sum up to currentIndex - startIndex where startIndex >= 0 (but > 0 in the interesting case). This changes the deserved reward in hindsight. Although this is the desired effect, the rule shows how we could actually claim more rewards if we were to collect our rewards before the

**Comment by sakulstra** [comment]
- closed by https://github.com/bgd-labs/static-a-token-v3/pull/29
